name: aria2-task-manager

on:
  workflow_dispatch:
  push:
    paths:
      - "app/**"
      - "package.json"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch external JS/CSS
        run: |
          curl -L -o app/common.css https://jc3213.github.io/download_with_aria2/chromium/pages/common.css
          curl -L -o app/popup.css https://jc3213.github.io/download_with_aria2/chromium/pages/popup/popup.css
          curl -L -o app/popup.js https://jc3213.github.io/download_with_aria2/chromium/pages/popup/popup.js

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run dist

      - name: Upload Electron build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build
          path: dist/

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add app/common.css app/popup.css app/popup.js
          git commit -m "Update external assets" || echo "No changes to commit"
          git push
