name: aria2-task-manager

on:
  push:
    paths:
      - "app/**"
      - "package.json"
      - "!app/common.css"
      - "!app/popup.css"
      - "!app/popup.js"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.assets }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            assets:
              - 'app/index.html'
              - 'app/index.js'

  assets:
    needs: check
    if: needs.check.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Fetch external JS/CSS
        run: |
          curl -L -o app/common.css https://jc3213.github.io/download_with_aria2/chromium/pages/common.css
          curl -L -o app/popup.css https://jc3213.github.io/download_with_aria2/chromium/pages/popup/popup.css
          curl -L -o app/popup.js https://jc3213.github.io/download_with_aria2/chromium/pages/popup/popup.js

      - name: Commit updated assets
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add app/common.css app/popup.css app/popup.js

          git diff --cached --quiet || git commit -m "Sync external assets [skip-sync]"
          git push

  prepare:
    needs: check
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pkg.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Read version
        id: pkg
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Delete old release if exists
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.pkg.outputs.version }}"
          if gh release view "$VERSION" >/dev/null 2>&1; then
            gh release delete "$VERSION" -y || true
            git push origin ":refs/tags/$VERSION" || true
          fi

      - name: Create new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.pkg.outputs.version }}"
          gh release create "$VERSION" --title "$VERSION" --notes "Auto release $VERSION"

  build:
    needs: [assets, prepare]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ needs.prepare.outputs.version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run dist

      - name: Upload installers (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          find dist -type f \( -name "*.dmg" -o -name "*.AppImage" -o -name "*.exe" \) | while read file; do
            gh release upload "$VERSION" "$file" --clobber
          done

      - name: Upload installers (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $version = $env:VERSION

          $zip = "aria2-task-manager-$version-win64.zip"
          Compress-Archive "dist/win-unpacked/*" $zip -Force

          $setup = Get-ChildItem dist -Filter "*Setup*.exe" | Select-Object -First 1
          $exe = "aria2-task-manager-$version-win64.exe"
          Copy-Item $setup.FullName $exe -Force

          gh release upload $version $zip --clobber
          gh release upload $version $exe --clobber
